<a href="https://colab.research.google.com/github/Huang-23/Huang-23.github.io/blob/master/B0729063_DFT_computation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
x= [1,
    2-1j,
    -1j,
    -1+2j]

In [ ]:
x= np.array(x)
x

array([ 1.+0.j,  2.-1.j, -0.-1.j, -1.+2.j])

In [ ]:
# [x0,x1,x2,x3] dot []

In [ ]:
x.size

4

In [ ]:
N= x.size
π= np.pi

In [ ]:
# k = 0,1,2,3,....,N-1
#k=1
#n=0,1,2,3,....,N-1

# np.exp(-1j*2*π/N *k *n)


n= np.arange(N)
k= np.arange(N)
n, k

(array([0, 1, 2, 3]), array([0, 1, 2, 3]))

In [ ]:
#
# DFT computation as a homework
#

x= [1,
    2-1j,
    -1j,
    -1+2j]
# X= ?

x= np.array(x)
N= x.size
π= np.pi

In [ ]:
# DFT solution ver001
aL= []
for k in range(N):
    s=0
    for n in range(N):
        s += x[n] * np.exp(-1j*2*π/N *k *n)    
    aL += [s]
X= np.array(aL)
X

array([ 2.0000000e+00+0.j, -2.0000000e+00-2.j,  8.8817842e-16-2.j,
        4.0000000e+00+4.j])

In [ ]:
# the answer
# array([ 2.0000000e+00+0.j, -2.0000000e+00-2.j,  8.8817842e-16-2.j,
#        4.0000000e+00+4.j])


In [ ]:
# DFT solution ver002

n= np.arange(N)

aL= []
for k in range(N):    
    e= np.exp(-1j*2*π/N *k *n)
    s= x @ e
    aL += [s]
X= np.array(aL)
X



array([ 2.00000000e+00+0.j, -2.00000000e+00-2.j,  8.57252759e-16-2.j,
        4.00000000e+00+4.j])

In [ ]:
# DFT solution ver003 
# 把它改成純矩陣運算。
# 參考 ... 
# https://greenteapress.com/thinkdsp/html/thinkdsp008.html

import numpy as np

π= np.pi

PI2= 2*π

def synthesis_matrix(N):
    ts = np.arange(N) / N
    fs = np.arange(N)
    args = np.outer(ts, fs)
    M = np.exp(1j * PI2 * args)
    return M

def dft(ys):
    N = len(ys)
    M = synthesis_matrix(N)
    amps = M.conj().transpose().dot(ys)
    return amps

X= dft(x)
X

array([ 2.0000000e+00+0.j, -2.0000000e+00-2.j,  8.8817842e-16-2.j,
        4.0000000e+00+4.j])

In [ ]:
# 上面 DFT solution ver003，改自課本的現成程式碼，
# 就是我所謂的純用矩陣，避免 緩慢的 for 迴圈。
# 請你改寫它成為更精簡的模式。 

In [ ]:
#---將ver003精簡---

import numpy as np

ts = np.arange(len(x)) / len(x)
fs = np.arange(len(x))
X = np.exp(1j * 2*np.pi * np.outer(ts, fs)).conj().dot(x)
X

array([ 2.0000000e+00+0.j, -2.0000000e+00-2.j,  8.8817842e-16-2.j,
        4.0000000e+00+4.j])

In [ ]:
#---用快速傅立葉變換更快---

import numpy as np

X= np.fft.fft(x)
X

array([ 2.+0.j, -2.-2.j,  0.-2.j,  4.+4.j])